{% set data = load_setup_py_data() %}

package:
  name: ked
  version: {{ data['version'] }}

source:
  path: ..
  
build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    {% for dep in data['install_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}

test:
  source_files:
    - tests
  requires:
    - pytest
    
about:
  home: https://github.com/harripj/KED
  license_file: LICENSE